### ISSUE TITLE
[Bug] 入力フォームのエラーハンドリング (AuthroOrder)

### ISSUE THREAD

**Issue by getty708** [getty708/PubZ#73]
AuthorOrderの数字の入力に関してエラーが生じている？

```
[20/Aug/2020 16:38:19] "GET /static/js/tether/dist/js/tether.min.js HTTP/1.1" 404 1720
[20/Aug/2020 16:38:26] "GET /core/edit/9843/ HTTP/1.1" 200 19577
[20/Aug/2020 16:38:26] "GET /static/js/tether/dist/js/tether.min.js HTTP/1.1" 404 1720
GET
Internal Server Error: /core/author/order/add
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/code/core/views_edit.py", line 193, in author_order_edit
    'submit_url': submit_url})
  File "/usr/local/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 993, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 972, in render_value_in_context
    value = str(value)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 388, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 33, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 241, in render
    context = self.get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 678, in get_context
    context = super().get_context(name, value, attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 639, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 587, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 1138, in __iter__
    yield self.choice(obj)
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 1150, in choice
    return (self.field.prepare_value(obj), self.field.label_from_instance(obj))
  File "/usr/local/lib/python3.7/site-packages/django/forms/models.py", line 1216, in label_from_instance
    return str(obj)
TypeError: __str__ returned non-string (type NoneType)
[20/Aug/2020 16:38:30] "GET /core/author/order/add?bibtex=9843 HTTP/1.1" 500 210933
netwg@web2:~/Codes/PubZ$
netwg@web2:~/Codes/PubZ$
```

**Comment by getty708** [comment]
なぜこのタイミングで出てきたかは不明であるが，モデルのstrメソッドがstr以外の値を返していることが原因らしい．

https://naruport.com/blog/2019/7/29/django-type-error-returned-non-string/


ひとまず無理やりstrでキャストして対処

**Comment by getty708** [comment]
- issue #75 で，日本語と英語に分割していたタイトルを一つに統合．
- タイトルは別のところで利用する場合はstrのキャストをかける．

以上の対応でこのissueをcloseする．
